CREATE TABLE IF NOT EXISTS daily_recommended_hotels (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  recommendation_date DATE NOT NULL,
  refresh_slot VARCHAR(32) NOT NULL,
  refresh_hours TINYINT UNSIGNED NOT NULL DEFAULT 6,
  city_name_zh VARCHAR(64) NOT NULL,
  holiday_code VARCHAR(64) NOT NULL,
  holiday_name_zh VARCHAR(80) DEFAULT NULL,
  hotel_id VARCHAR(64) NOT NULL,
  hotel_name_zh VARCHAR(255) NOT NULL,
  hotel_name_original VARCHAR(255) DEFAULT NULL,
  hotel_name_source VARCHAR(80) DEFAULT NULL,
  area_name_zh VARCHAR(128) DEFAULT NULL,
  detail_url VARCHAR(1024) DEFAULT NULL,
  image_url VARCHAR(1024) DEFAULT NULL,
  room_type_label VARCHAR(80) DEFAULT NULL,
  is_advanced TINYINT(1) DEFAULT NULL,
  has_pool TINYINT(1) DEFAULT NULL,
  has_child_facility TINYINT(1) DEFAULT NULL,
  holiday_avg_nightly_tax_total_cny DECIMAL(10,2) DEFAULT NULL,
  holiday_tax_total_cny DECIMAL(10,2) DEFAULT NULL,
  comparison_avg_nightly_tax_total_cny DECIMAL(10,2) DEFAULT NULL,
  comparison_lowest_nightly_tax_total_cny DECIMAL(10,2) DEFAULT NULL,
  comparison_lowest_check_in DATE DEFAULT NULL,
  comparison_lowest_check_out DATE DEFAULT NULL,
  comparison_sample_count INT UNSIGNED NOT NULL DEFAULT 0,
  price_diff_nightly_cny DECIMAL(10,2) DEFAULT NULL,
  cache_created_at DATETIME DEFAULT NULL,
  cache_age_seconds INT UNSIGNED DEFAULT NULL,
  cache_key_json JSON DEFAULT NULL,
  feature_filters_json JSON DEFAULT NULL,
  hotel_payload_json JSON DEFAULT NULL,
  selected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_daily_recommended_hotels_slot (refresh_slot),
  KEY idx_daily_recommended_hotels_date (recommendation_date, selected_at),
  KEY idx_daily_recommended_hotels_hotel (hotel_id, selected_at),
  KEY idx_daily_recommended_hotels_city_holiday (city_name_zh, holiday_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
